#!/usr/bin/env python3
"""
Generate C++ sources for built-in k-mer models from provided text tables.

Inputs:
  - R9.4 6-mer model with mean/stdv columns (legacy template_median68pA.model)
  - R10.4 9-mer model with mean column (stdv filled with a default)

Outputs (written to an output directory):
  - builtin_model_common.hpp: shared ModelEntry struct
  - builtin_model_r9.hpp (and .cpp unless --header-only is set)
  - builtin_model_r10.hpp (and .cpp unless --header-only is set)
"""

import argparse
from pathlib import Path
from typing import Iterable, List, Tuple


Entry = Tuple[str, float]


def parse_r9(path: Path) -> List[Entry]:
    lines = path.read_text().splitlines()
    entries: List[Entry] = []
    for line in lines[1:]:  # skip header
        if not line.strip():
            continue
        parts = line.split()
        if len(parts) < 3:
            continue
        kmer, mean = parts[0], float(parts[1])
        entries.append((kmer, mean))
    return entries


def parse_r10(path: Path, default_stdv: float) -> List[Entry]:
    entries: List[Entry] = []
    for line in path.read_text().splitlines():
        if not line.strip():
            continue
        # Skip comment lines (e.g., #ont_model_name, #kit, etc.)
        if line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        kmer = parts[0]
        # Skip header line (kmer column contains "kmer" not ACGT sequence)
        if not all(c in "ACGT" for c in kmer):
            continue
        mean = float(parts[1])
        entries.append((kmer, mean))
    return entries


def format_entries(entries: Iterable[Entry]) -> str:
    lines = []
    for kmer, mean in entries:
        lines.append(f'    {{"{kmer}", {mean:.10g}}},')
    return "\n".join(lines)


def write_common_header(path: Path) -> None:
    path.write_text(
        "\n".join(
            [
                "// @generated by tools/generate_builtin_models.py; DO NOT EDIT.",
                "#pragma once",
                "",
                "#include <cstddef>",
        "",
        "namespace panomap::io::generated {",
        "",
        "struct ModelEntry {",
        "    const char* kmer;",
        "    double mean;",
        "};",
                "",
                "}  // namespace panomap::io::generated",
                "",
            ]
        )
    )


def write_model_files(
    common_header: str,
    header_path: Path,
    source_path: Path,
    entries: List[Entry],
    kmer_size: int,
    prefix: str,
    header_only: bool,
) -> None:
    header_lines = [
        "// @generated by tools/generate_builtin_models.py; DO NOT EDIT.",
        "#pragma once",
        "",
        f'#include "{common_header}"',
        "",
        "namespace panomap::io::generated {",
        "",
        f"inline constexpr int k{prefix}K = {kmer_size};",
        f"inline constexpr std::size_t k{prefix}Count = {len(entries)};",
    ]

    if header_only:
        header_lines.extend(
            [
                f"inline constexpr ModelEntry k{prefix}Entries[k{prefix}Count] = {{",
                format_entries(entries),
                "};",
            ]
        )
    else:
        header_lines.append(f"extern const ModelEntry k{prefix}Entries[k{prefix}Count];")

    header_lines.extend(
        [
            "",
            "}  // namespace panomap::io::generated",
            "",
        ]
    )
    header_path.write_text("\n".join(header_lines))

    if header_only:
        return

    source_path.write_text(
        "\n".join(
            [
                "// @generated by tools/generate_builtin_models.py; DO NOT EDIT.",
                f'#include "{header_path.name}"',
                "",
                "namespace panomap::io::generated {",
                "",
                f"const ModelEntry k{prefix}Entries[k{prefix}Count] = {{",
                format_entries(entries),
                "};",
                "",
                "}  // namespace panomap::io::generated",
                "",
            ]
        )
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate built-in k-mer model data.")
    parser.add_argument("--r9", type=Path, required=True, help="Path to R9.4 model file")
    parser.add_argument("--r10", type=Path, required=True, help="Path to R10.4 model file")
    parser.add_argument("--out-dir", type=Path, required=True, help="Output directory for generated files")
    parser.add_argument("--header-only", action="store_true", help="Emit header-only model tables (no .cpp files)")
    parser.add_argument(
        "--r10-stdv",
        type=float,
        default=1.0,
        help="Default stdv value for R10.4 entries (file only provides mean)",
    )
    args = parser.parse_args()

    r9_entries = parse_r9(args.r9)
    r10_entries = parse_r10(args.r10, args.r10_stdv)

    args.out_dir.mkdir(parents=True, exist_ok=True)

    header_only = args.header_only
    common_header = args.out_dir / "builtin_model_common.hpp"
    write_common_header(common_header)

    write_model_files(
        common_header.name,
        args.out_dir / "builtin_model_r9.hpp",
        args.out_dir / "builtin_model_r9.cpp",
        r9_entries,
        kmer_size=6,
        prefix="R9",
        header_only=header_only,
    )
    write_model_files(
        common_header.name,
        args.out_dir / "builtin_model_r10.hpp",
        args.out_dir / "builtin_model_r10.cpp",
        r10_entries,
        kmer_size=9,
        prefix="R10",
        header_only=header_only,
    )


if __name__ == "__main__":
    main()
