// @generated by tools/generate_builtin_models.py; DO NOT EDIT.
#pragma once

#include <cstddef>

namespace panomap::io::generated {

struct ModelEntry {
  const char* kmer;
  double mean;
};

}  // namespace panomap::io::generated
